services:
  - type: web
    name: task-manager-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: task-manager-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: task-manager-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: task-manager-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: task-manager-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: task-manager-db
          property: database

databases:
  - name: task-manager-db
    plan: free 